################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/StatisticsFunctions/StatisticsFunctions.c \
../src/StatisticsFunctions/StatisticsFunctionsF16.c \
../src/StatisticsFunctions/arm_absmax_f16.c \
../src/StatisticsFunctions/arm_absmax_f32.c \
../src/StatisticsFunctions/arm_absmax_f64.c \
../src/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../src/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../src/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../src/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../src/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../src/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../src/StatisticsFunctions/arm_absmax_q15.c \
../src/StatisticsFunctions/arm_absmax_q31.c \
../src/StatisticsFunctions/arm_absmax_q7.c \
../src/StatisticsFunctions/arm_absmin_f16.c \
../src/StatisticsFunctions/arm_absmin_f32.c \
../src/StatisticsFunctions/arm_absmin_f64.c \
../src/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../src/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../src/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../src/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../src/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../src/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../src/StatisticsFunctions/arm_absmin_q15.c \
../src/StatisticsFunctions/arm_absmin_q31.c \
../src/StatisticsFunctions/arm_absmin_q7.c \
../src/StatisticsFunctions/arm_accumulate_f16.c \
../src/StatisticsFunctions/arm_accumulate_f32.c \
../src/StatisticsFunctions/arm_accumulate_f64.c \
../src/StatisticsFunctions/arm_entropy_f16.c \
../src/StatisticsFunctions/arm_entropy_f32.c \
../src/StatisticsFunctions/arm_entropy_f64.c \
../src/StatisticsFunctions/arm_kullback_leibler_f16.c \
../src/StatisticsFunctions/arm_kullback_leibler_f32.c \
../src/StatisticsFunctions/arm_kullback_leibler_f64.c \
../src/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../src/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../src/StatisticsFunctions/arm_logsumexp_f16.c \
../src/StatisticsFunctions/arm_logsumexp_f32.c \
../src/StatisticsFunctions/arm_max_f16.c \
../src/StatisticsFunctions/arm_max_f32.c \
../src/StatisticsFunctions/arm_max_f64.c \
../src/StatisticsFunctions/arm_max_no_idx_f16.c \
../src/StatisticsFunctions/arm_max_no_idx_f32.c \
../src/StatisticsFunctions/arm_max_no_idx_f64.c \
../src/StatisticsFunctions/arm_max_no_idx_q15.c \
../src/StatisticsFunctions/arm_max_no_idx_q31.c \
../src/StatisticsFunctions/arm_max_no_idx_q7.c \
../src/StatisticsFunctions/arm_max_q15.c \
../src/StatisticsFunctions/arm_max_q31.c \
../src/StatisticsFunctions/arm_max_q7.c \
../src/StatisticsFunctions/arm_mean_f16.c \
../src/StatisticsFunctions/arm_mean_f32.c \
../src/StatisticsFunctions/arm_mean_f64.c \
../src/StatisticsFunctions/arm_mean_q15.c \
../src/StatisticsFunctions/arm_mean_q31.c \
../src/StatisticsFunctions/arm_mean_q7.c \
../src/StatisticsFunctions/arm_min_f16.c \
../src/StatisticsFunctions/arm_min_f32.c \
../src/StatisticsFunctions/arm_min_f64.c \
../src/StatisticsFunctions/arm_min_no_idx_f16.c \
../src/StatisticsFunctions/arm_min_no_idx_f32.c \
../src/StatisticsFunctions/arm_min_no_idx_f64.c \
../src/StatisticsFunctions/arm_min_no_idx_q15.c \
../src/StatisticsFunctions/arm_min_no_idx_q31.c \
../src/StatisticsFunctions/arm_min_no_idx_q7.c \
../src/StatisticsFunctions/arm_min_q15.c \
../src/StatisticsFunctions/arm_min_q31.c \
../src/StatisticsFunctions/arm_min_q7.c \
../src/StatisticsFunctions/arm_mse_f16.c \
../src/StatisticsFunctions/arm_mse_f32.c \
../src/StatisticsFunctions/arm_mse_f64.c \
../src/StatisticsFunctions/arm_mse_q15.c \
../src/StatisticsFunctions/arm_mse_q31.c \
../src/StatisticsFunctions/arm_mse_q7.c \
../src/StatisticsFunctions/arm_power_f16.c \
../src/StatisticsFunctions/arm_power_f32.c \
../src/StatisticsFunctions/arm_power_f64.c \
../src/StatisticsFunctions/arm_power_q15.c \
../src/StatisticsFunctions/arm_power_q31.c \
../src/StatisticsFunctions/arm_power_q7.c \
../src/StatisticsFunctions/arm_rms_f16.c \
../src/StatisticsFunctions/arm_rms_f32.c \
../src/StatisticsFunctions/arm_rms_q15.c \
../src/StatisticsFunctions/arm_rms_q31.c \
../src/StatisticsFunctions/arm_std_f16.c \
../src/StatisticsFunctions/arm_std_f32.c \
../src/StatisticsFunctions/arm_std_f64.c \
../src/StatisticsFunctions/arm_std_q15.c \
../src/StatisticsFunctions/arm_std_q31.c \
../src/StatisticsFunctions/arm_var_f16.c \
../src/StatisticsFunctions/arm_var_f32.c \
../src/StatisticsFunctions/arm_var_f64.c \
../src/StatisticsFunctions/arm_var_q15.c \
../src/StatisticsFunctions/arm_var_q31.c 

C_DEPS += \
./src/StatisticsFunctions/StatisticsFunctions.d \
./src/StatisticsFunctions/StatisticsFunctionsF16.d \
./src/StatisticsFunctions/arm_absmax_f16.d \
./src/StatisticsFunctions/arm_absmax_f32.d \
./src/StatisticsFunctions/arm_absmax_f64.d \
./src/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./src/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./src/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./src/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./src/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./src/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./src/StatisticsFunctions/arm_absmax_q15.d \
./src/StatisticsFunctions/arm_absmax_q31.d \
./src/StatisticsFunctions/arm_absmax_q7.d \
./src/StatisticsFunctions/arm_absmin_f16.d \
./src/StatisticsFunctions/arm_absmin_f32.d \
./src/StatisticsFunctions/arm_absmin_f64.d \
./src/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./src/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./src/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./src/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./src/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./src/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./src/StatisticsFunctions/arm_absmin_q15.d \
./src/StatisticsFunctions/arm_absmin_q31.d \
./src/StatisticsFunctions/arm_absmin_q7.d \
./src/StatisticsFunctions/arm_accumulate_f16.d \
./src/StatisticsFunctions/arm_accumulate_f32.d \
./src/StatisticsFunctions/arm_accumulate_f64.d \
./src/StatisticsFunctions/arm_entropy_f16.d \
./src/StatisticsFunctions/arm_entropy_f32.d \
./src/StatisticsFunctions/arm_entropy_f64.d \
./src/StatisticsFunctions/arm_kullback_leibler_f16.d \
./src/StatisticsFunctions/arm_kullback_leibler_f32.d \
./src/StatisticsFunctions/arm_kullback_leibler_f64.d \
./src/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./src/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./src/StatisticsFunctions/arm_logsumexp_f16.d \
./src/StatisticsFunctions/arm_logsumexp_f32.d \
./src/StatisticsFunctions/arm_max_f16.d \
./src/StatisticsFunctions/arm_max_f32.d \
./src/StatisticsFunctions/arm_max_f64.d \
./src/StatisticsFunctions/arm_max_no_idx_f16.d \
./src/StatisticsFunctions/arm_max_no_idx_f32.d \
./src/StatisticsFunctions/arm_max_no_idx_f64.d \
./src/StatisticsFunctions/arm_max_no_idx_q15.d \
./src/StatisticsFunctions/arm_max_no_idx_q31.d \
./src/StatisticsFunctions/arm_max_no_idx_q7.d \
./src/StatisticsFunctions/arm_max_q15.d \
./src/StatisticsFunctions/arm_max_q31.d \
./src/StatisticsFunctions/arm_max_q7.d \
./src/StatisticsFunctions/arm_mean_f16.d \
./src/StatisticsFunctions/arm_mean_f32.d \
./src/StatisticsFunctions/arm_mean_f64.d \
./src/StatisticsFunctions/arm_mean_q15.d \
./src/StatisticsFunctions/arm_mean_q31.d \
./src/StatisticsFunctions/arm_mean_q7.d \
./src/StatisticsFunctions/arm_min_f16.d \
./src/StatisticsFunctions/arm_min_f32.d \
./src/StatisticsFunctions/arm_min_f64.d \
./src/StatisticsFunctions/arm_min_no_idx_f16.d \
./src/StatisticsFunctions/arm_min_no_idx_f32.d \
./src/StatisticsFunctions/arm_min_no_idx_f64.d \
./src/StatisticsFunctions/arm_min_no_idx_q15.d \
./src/StatisticsFunctions/arm_min_no_idx_q31.d \
./src/StatisticsFunctions/arm_min_no_idx_q7.d \
./src/StatisticsFunctions/arm_min_q15.d \
./src/StatisticsFunctions/arm_min_q31.d \
./src/StatisticsFunctions/arm_min_q7.d \
./src/StatisticsFunctions/arm_mse_f16.d \
./src/StatisticsFunctions/arm_mse_f32.d \
./src/StatisticsFunctions/arm_mse_f64.d \
./src/StatisticsFunctions/arm_mse_q15.d \
./src/StatisticsFunctions/arm_mse_q31.d \
./src/StatisticsFunctions/arm_mse_q7.d \
./src/StatisticsFunctions/arm_power_f16.d \
./src/StatisticsFunctions/arm_power_f32.d \
./src/StatisticsFunctions/arm_power_f64.d \
./src/StatisticsFunctions/arm_power_q15.d \
./src/StatisticsFunctions/arm_power_q31.d \
./src/StatisticsFunctions/arm_power_q7.d \
./src/StatisticsFunctions/arm_rms_f16.d \
./src/StatisticsFunctions/arm_rms_f32.d \
./src/StatisticsFunctions/arm_rms_q15.d \
./src/StatisticsFunctions/arm_rms_q31.d \
./src/StatisticsFunctions/arm_std_f16.d \
./src/StatisticsFunctions/arm_std_f32.d \
./src/StatisticsFunctions/arm_std_f64.d \
./src/StatisticsFunctions/arm_std_q15.d \
./src/StatisticsFunctions/arm_std_q31.d \
./src/StatisticsFunctions/arm_var_f16.d \
./src/StatisticsFunctions/arm_var_f32.d \
./src/StatisticsFunctions/arm_var_f64.d \
./src/StatisticsFunctions/arm_var_q15.d \
./src/StatisticsFunctions/arm_var_q31.d 

OBJS += \
./src/StatisticsFunctions/StatisticsFunctions.o \
./src/StatisticsFunctions/StatisticsFunctionsF16.o \
./src/StatisticsFunctions/arm_absmax_f16.o \
./src/StatisticsFunctions/arm_absmax_f32.o \
./src/StatisticsFunctions/arm_absmax_f64.o \
./src/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./src/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./src/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./src/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./src/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./src/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./src/StatisticsFunctions/arm_absmax_q15.o \
./src/StatisticsFunctions/arm_absmax_q31.o \
./src/StatisticsFunctions/arm_absmax_q7.o \
./src/StatisticsFunctions/arm_absmin_f16.o \
./src/StatisticsFunctions/arm_absmin_f32.o \
./src/StatisticsFunctions/arm_absmin_f64.o \
./src/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./src/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./src/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./src/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./src/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./src/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./src/StatisticsFunctions/arm_absmin_q15.o \
./src/StatisticsFunctions/arm_absmin_q31.o \
./src/StatisticsFunctions/arm_absmin_q7.o \
./src/StatisticsFunctions/arm_accumulate_f16.o \
./src/StatisticsFunctions/arm_accumulate_f32.o \
./src/StatisticsFunctions/arm_accumulate_f64.o \
./src/StatisticsFunctions/arm_entropy_f16.o \
./src/StatisticsFunctions/arm_entropy_f32.o \
./src/StatisticsFunctions/arm_entropy_f64.o \
./src/StatisticsFunctions/arm_kullback_leibler_f16.o \
./src/StatisticsFunctions/arm_kullback_leibler_f32.o \
./src/StatisticsFunctions/arm_kullback_leibler_f64.o \
./src/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./src/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./src/StatisticsFunctions/arm_logsumexp_f16.o \
./src/StatisticsFunctions/arm_logsumexp_f32.o \
./src/StatisticsFunctions/arm_max_f16.o \
./src/StatisticsFunctions/arm_max_f32.o \
./src/StatisticsFunctions/arm_max_f64.o \
./src/StatisticsFunctions/arm_max_no_idx_f16.o \
./src/StatisticsFunctions/arm_max_no_idx_f32.o \
./src/StatisticsFunctions/arm_max_no_idx_f64.o \
./src/StatisticsFunctions/arm_max_no_idx_q15.o \
./src/StatisticsFunctions/arm_max_no_idx_q31.o \
./src/StatisticsFunctions/arm_max_no_idx_q7.o \
./src/StatisticsFunctions/arm_max_q15.o \
./src/StatisticsFunctions/arm_max_q31.o \
./src/StatisticsFunctions/arm_max_q7.o \
./src/StatisticsFunctions/arm_mean_f16.o \
./src/StatisticsFunctions/arm_mean_f32.o \
./src/StatisticsFunctions/arm_mean_f64.o \
./src/StatisticsFunctions/arm_mean_q15.o \
./src/StatisticsFunctions/arm_mean_q31.o \
./src/StatisticsFunctions/arm_mean_q7.o \
./src/StatisticsFunctions/arm_min_f16.o \
./src/StatisticsFunctions/arm_min_f32.o \
./src/StatisticsFunctions/arm_min_f64.o \
./src/StatisticsFunctions/arm_min_no_idx_f16.o \
./src/StatisticsFunctions/arm_min_no_idx_f32.o \
./src/StatisticsFunctions/arm_min_no_idx_f64.o \
./src/StatisticsFunctions/arm_min_no_idx_q15.o \
./src/StatisticsFunctions/arm_min_no_idx_q31.o \
./src/StatisticsFunctions/arm_min_no_idx_q7.o \
./src/StatisticsFunctions/arm_min_q15.o \
./src/StatisticsFunctions/arm_min_q31.o \
./src/StatisticsFunctions/arm_min_q7.o \
./src/StatisticsFunctions/arm_mse_f16.o \
./src/StatisticsFunctions/arm_mse_f32.o \
./src/StatisticsFunctions/arm_mse_f64.o \
./src/StatisticsFunctions/arm_mse_q15.o \
./src/StatisticsFunctions/arm_mse_q31.o \
./src/StatisticsFunctions/arm_mse_q7.o \
./src/StatisticsFunctions/arm_power_f16.o \
./src/StatisticsFunctions/arm_power_f32.o \
./src/StatisticsFunctions/arm_power_f64.o \
./src/StatisticsFunctions/arm_power_q15.o \
./src/StatisticsFunctions/arm_power_q31.o \
./src/StatisticsFunctions/arm_power_q7.o \
./src/StatisticsFunctions/arm_rms_f16.o \
./src/StatisticsFunctions/arm_rms_f32.o \
./src/StatisticsFunctions/arm_rms_q15.o \
./src/StatisticsFunctions/arm_rms_q31.o \
./src/StatisticsFunctions/arm_std_f16.o \
./src/StatisticsFunctions/arm_std_f32.o \
./src/StatisticsFunctions/arm_std_f64.o \
./src/StatisticsFunctions/arm_std_q15.o \
./src/StatisticsFunctions/arm_std_q31.o \
./src/StatisticsFunctions/arm_var_f16.o \
./src/StatisticsFunctions/arm_var_f32.o \
./src/StatisticsFunctions/arm_var_f64.o \
./src/StatisticsFunctions/arm_var_q15.o \
./src/StatisticsFunctions/arm_var_q31.o 


# Each subdirectory must supply rules for building sources it contributes
src/StatisticsFunctions/%.o: ../src/StatisticsFunctions/%.c src/StatisticsFunctions/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -DDEBUG -D__CODE_RED -D__REDLIB__ -DCORE_M4 -D__USE_LPCOPEN -D__LPC43XX__ -I"/media/carlassaraf/DATA/facultad/TD III/2022_td3_512_carlassara/3.workspace/cmsis_dsp/inc" -I"/media/carlassaraf/DATA/facultad/TD III/2022_td3_512_carlassara/3.workspace/chip/lpc_chip_43xx/inc" -O0 -fno-common -g3 -Wall -c -fmessage-length=0 -fno-builtin -ffunction-sections -fdata-sections -fsingle-precision-constant -fmerge-constants -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -mthumb -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


clean: clean-src-2f-StatisticsFunctions

clean-src-2f-StatisticsFunctions:
	-$(RM) ./src/StatisticsFunctions/StatisticsFunctions.d ./src/StatisticsFunctions/StatisticsFunctions.o ./src/StatisticsFunctions/StatisticsFunctionsF16.d ./src/StatisticsFunctions/StatisticsFunctionsF16.o ./src/StatisticsFunctions/arm_absmax_f16.d ./src/StatisticsFunctions/arm_absmax_f16.o ./src/StatisticsFunctions/arm_absmax_f32.d ./src/StatisticsFunctions/arm_absmax_f32.o ./src/StatisticsFunctions/arm_absmax_f64.d ./src/StatisticsFunctions/arm_absmax_f64.o ./src/StatisticsFunctions/arm_absmax_no_idx_f16.d ./src/StatisticsFunctions/arm_absmax_no_idx_f16.o ./src/StatisticsFunctions/arm_absmax_no_idx_f32.d ./src/StatisticsFunctions/arm_absmax_no_idx_f32.o ./src/StatisticsFunctions/arm_absmax_no_idx_f64.d ./src/StatisticsFunctions/arm_absmax_no_idx_f64.o ./src/StatisticsFunctions/arm_absmax_no_idx_q15.d ./src/StatisticsFunctions/arm_absmax_no_idx_q15.o ./src/StatisticsFunctions/arm_absmax_no_idx_q31.d ./src/StatisticsFunctions/arm_absmax_no_idx_q31.o ./src/StatisticsFunctions/arm_absmax_no_idx_q7.d ./src/StatisticsFunctions/arm_absmax_no_idx_q7.o ./src/StatisticsFunctions/arm_absmax_q15.d ./src/StatisticsFunctions/arm_absmax_q15.o ./src/StatisticsFunctions/arm_absmax_q31.d ./src/StatisticsFunctions/arm_absmax_q31.o ./src/StatisticsFunctions/arm_absmax_q7.d ./src/StatisticsFunctions/arm_absmax_q7.o ./src/StatisticsFunctions/arm_absmin_f16.d ./src/StatisticsFunctions/arm_absmin_f16.o ./src/StatisticsFunctions/arm_absmin_f32.d ./src/StatisticsFunctions/arm_absmin_f32.o ./src/StatisticsFunctions/arm_absmin_f64.d ./src/StatisticsFunctions/arm_absmin_f64.o ./src/StatisticsFunctions/arm_absmin_no_idx_f16.d ./src/StatisticsFunctions/arm_absmin_no_idx_f16.o ./src/StatisticsFunctions/arm_absmin_no_idx_f32.d ./src/StatisticsFunctions/arm_absmin_no_idx_f32.o ./src/StatisticsFunctions/arm_absmin_no_idx_f64.d ./src/StatisticsFunctions/arm_absmin_no_idx_f64.o ./src/StatisticsFunctions/arm_absmin_no_idx_q15.d ./src/StatisticsFunctions/arm_absmin_no_idx_q15.o ./src/StatisticsFunctions/arm_absmin_no_idx_q31.d ./src/StatisticsFunctions/arm_absmin_no_idx_q31.o ./src/StatisticsFunctions/arm_absmin_no_idx_q7.d ./src/StatisticsFunctions/arm_absmin_no_idx_q7.o ./src/StatisticsFunctions/arm_absmin_q15.d ./src/StatisticsFunctions/arm_absmin_q15.o ./src/StatisticsFunctions/arm_absmin_q31.d ./src/StatisticsFunctions/arm_absmin_q31.o ./src/StatisticsFunctions/arm_absmin_q7.d ./src/StatisticsFunctions/arm_absmin_q7.o ./src/StatisticsFunctions/arm_accumulate_f16.d ./src/StatisticsFunctions/arm_accumulate_f16.o ./src/StatisticsFunctions/arm_accumulate_f32.d ./src/StatisticsFunctions/arm_accumulate_f32.o ./src/StatisticsFunctions/arm_accumulate_f64.d ./src/StatisticsFunctions/arm_accumulate_f64.o ./src/StatisticsFunctions/arm_entropy_f16.d ./src/StatisticsFunctions/arm_entropy_f16.o ./src/StatisticsFunctions/arm_entropy_f32.d ./src/StatisticsFunctions/arm_entropy_f32.o ./src/StatisticsFunctions/arm_entropy_f64.d ./src/StatisticsFunctions/arm_entropy_f64.o ./src/StatisticsFunctions/arm_kullback_leibler_f16.d ./src/StatisticsFunctions/arm_kullback_leibler_f16.o ./src/StatisticsFunctions/arm_kullback_leibler_f32.d ./src/StatisticsFunctions/arm_kullback_leibler_f32.o ./src/StatisticsFunctions/arm_kullback_leibler_f64.d ./src/StatisticsFunctions/arm_kullback_leibler_f64.o ./src/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./src/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./src/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./src/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./src/StatisticsFunctions/arm_logsumexp_f16.d ./src/StatisticsFunctions/arm_logsumexp_f16.o ./src/StatisticsFunctions/arm_logsumexp_f32.d ./src/StatisticsFunctions/arm_logsumexp_f32.o ./src/StatisticsFunctions/arm_max_f16.d ./src/StatisticsFunctions/arm_max_f16.o ./src/StatisticsFunctions/arm_max_f32.d ./src/StatisticsFunctions/arm_max_f32.o ./src/StatisticsFunctions/arm_max_f64.d ./src/StatisticsFunctions/arm_max_f64.o ./src/StatisticsFunctions/arm_max_no_idx_f16.d ./src/StatisticsFunctions/arm_max_no_idx_f16.o ./src/StatisticsFunctions/arm_max_no_idx_f32.d ./src/StatisticsFunctions/arm_max_no_idx_f32.o ./src/StatisticsFunctions/arm_max_no_idx_f64.d ./src/StatisticsFunctions/arm_max_no_idx_f64.o ./src/StatisticsFunctions/arm_max_no_idx_q15.d ./src/StatisticsFunctions/arm_max_no_idx_q15.o ./src/StatisticsFunctions/arm_max_no_idx_q31.d ./src/StatisticsFunctions/arm_max_no_idx_q31.o ./src/StatisticsFunctions/arm_max_no_idx_q7.d ./src/StatisticsFunctions/arm_max_no_idx_q7.o ./src/StatisticsFunctions/arm_max_q15.d ./src/StatisticsFunctions/arm_max_q15.o ./src/StatisticsFunctions/arm_max_q31.d ./src/StatisticsFunctions/arm_max_q31.o ./src/StatisticsFunctions/arm_max_q7.d ./src/StatisticsFunctions/arm_max_q7.o ./src/StatisticsFunctions/arm_mean_f16.d ./src/StatisticsFunctions/arm_mean_f16.o ./src/StatisticsFunctions/arm_mean_f32.d ./src/StatisticsFunctions/arm_mean_f32.o ./src/StatisticsFunctions/arm_mean_f64.d ./src/StatisticsFunctions/arm_mean_f64.o ./src/StatisticsFunctions/arm_mean_q15.d ./src/StatisticsFunctions/arm_mean_q15.o ./src/StatisticsFunctions/arm_mean_q31.d ./src/StatisticsFunctions/arm_mean_q31.o ./src/StatisticsFunctions/arm_mean_q7.d ./src/StatisticsFunctions/arm_mean_q7.o ./src/StatisticsFunctions/arm_min_f16.d ./src/StatisticsFunctions/arm_min_f16.o ./src/StatisticsFunctions/arm_min_f32.d ./src/StatisticsFunctions/arm_min_f32.o ./src/StatisticsFunctions/arm_min_f64.d ./src/StatisticsFunctions/arm_min_f64.o ./src/StatisticsFunctions/arm_min_no_idx_f16.d ./src/StatisticsFunctions/arm_min_no_idx_f16.o ./src/StatisticsFunctions/arm_min_no_idx_f32.d ./src/StatisticsFunctions/arm_min_no_idx_f32.o ./src/StatisticsFunctions/arm_min_no_idx_f64.d ./src/StatisticsFunctions/arm_min_no_idx_f64.o ./src/StatisticsFunctions/arm_min_no_idx_q15.d ./src/StatisticsFunctions/arm_min_no_idx_q15.o ./src/StatisticsFunctions/arm_min_no_idx_q31.d ./src/StatisticsFunctions/arm_min_no_idx_q31.o ./src/StatisticsFunctions/arm_min_no_idx_q7.d
	-$(RM) ./src/StatisticsFunctions/arm_min_no_idx_q7.o ./src/StatisticsFunctions/arm_min_q15.d ./src/StatisticsFunctions/arm_min_q15.o ./src/StatisticsFunctions/arm_min_q31.d ./src/StatisticsFunctions/arm_min_q31.o ./src/StatisticsFunctions/arm_min_q7.d ./src/StatisticsFunctions/arm_min_q7.o ./src/StatisticsFunctions/arm_mse_f16.d ./src/StatisticsFunctions/arm_mse_f16.o ./src/StatisticsFunctions/arm_mse_f32.d ./src/StatisticsFunctions/arm_mse_f32.o ./src/StatisticsFunctions/arm_mse_f64.d ./src/StatisticsFunctions/arm_mse_f64.o ./src/StatisticsFunctions/arm_mse_q15.d ./src/StatisticsFunctions/arm_mse_q15.o ./src/StatisticsFunctions/arm_mse_q31.d ./src/StatisticsFunctions/arm_mse_q31.o ./src/StatisticsFunctions/arm_mse_q7.d ./src/StatisticsFunctions/arm_mse_q7.o ./src/StatisticsFunctions/arm_power_f16.d ./src/StatisticsFunctions/arm_power_f16.o ./src/StatisticsFunctions/arm_power_f32.d ./src/StatisticsFunctions/arm_power_f32.o ./src/StatisticsFunctions/arm_power_f64.d ./src/StatisticsFunctions/arm_power_f64.o ./src/StatisticsFunctions/arm_power_q15.d ./src/StatisticsFunctions/arm_power_q15.o ./src/StatisticsFunctions/arm_power_q31.d ./src/StatisticsFunctions/arm_power_q31.o ./src/StatisticsFunctions/arm_power_q7.d ./src/StatisticsFunctions/arm_power_q7.o ./src/StatisticsFunctions/arm_rms_f16.d ./src/StatisticsFunctions/arm_rms_f16.o ./src/StatisticsFunctions/arm_rms_f32.d ./src/StatisticsFunctions/arm_rms_f32.o ./src/StatisticsFunctions/arm_rms_q15.d ./src/StatisticsFunctions/arm_rms_q15.o ./src/StatisticsFunctions/arm_rms_q31.d ./src/StatisticsFunctions/arm_rms_q31.o ./src/StatisticsFunctions/arm_std_f16.d ./src/StatisticsFunctions/arm_std_f16.o ./src/StatisticsFunctions/arm_std_f32.d ./src/StatisticsFunctions/arm_std_f32.o ./src/StatisticsFunctions/arm_std_f64.d ./src/StatisticsFunctions/arm_std_f64.o ./src/StatisticsFunctions/arm_std_q15.d ./src/StatisticsFunctions/arm_std_q15.o ./src/StatisticsFunctions/arm_std_q31.d ./src/StatisticsFunctions/arm_std_q31.o ./src/StatisticsFunctions/arm_var_f16.d ./src/StatisticsFunctions/arm_var_f16.o ./src/StatisticsFunctions/arm_var_f32.d ./src/StatisticsFunctions/arm_var_f32.o ./src/StatisticsFunctions/arm_var_f64.d ./src/StatisticsFunctions/arm_var_f64.o ./src/StatisticsFunctions/arm_var_q15.d ./src/StatisticsFunctions/arm_var_q15.o ./src/StatisticsFunctions/arm_var_q31.d ./src/StatisticsFunctions/arm_var_q31.o

.PHONY: clean-src-2f-StatisticsFunctions

